# -*- coding: utf-8 -*-
"""Clase 4 Dudbil

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QMpw3e0yXMQ9M9AKZX2h3H2194HXKm7H

#CLASE 4: DATASETS


1.   Importar un dataset
2.   Descripción de variables
3.   Visualización
"""

import pandas as pd # Importa la librería pandas para trabajar con DataFrames

from google.colab import drive # Importa drive desde google.colab
drive.mount('/content/drive') # Monta Google Drive para acceder a archivos

data = pd.read_csv('/content/drive/MyDrive/ciencia_de_datos/credit_card.csv') # Carga el dataset desde un archivo CSV en un DataFrame llamado 'data'

data.info() # Muestra un resumen conciso del DataFrame, incluyendo tipos de datos y valores no nulos

data['CODE_GENDER'].info() # Muestra información específica de la columna 'CODE_GENDER'

round(data.describe()) # Muestra estadísticas descriptivas de las columnas numéricas y redondea los valores

data.isnull().sum() # Cuenta el número de valores nulos (missing values) por cada columna

data.value_counts() # Cuenta la ocurrencia de cada combinación única de valores en todas las columnas

data.value_counts('CODE_GENDER') # Cuenta la ocurrencia de cada valor único en la columna 'CODE_GENDER'

data.value_counts('NAME_CONTRACT_TYPE') # Cuenta la ocurrencia de cada valor único en la columna 'NAME_CONTRACT_TYPE'

data.value_counts('FLAG_OWN_CAR') # Cuenta la ocurrencia de cada valor único en la columna 'FLAG_OWN_CAR'

data.value_counts('FLAG_OWN_REALTY') # Cuenta la ocurrencia de cada valor único en la columna 'FLAG_OWN_REALTY'

data.value_counts('NAME_INCOME_TYPE') # Cuenta la ocurrencia de cada valor único en la columna 'NAME_INCOME_TYPE'

data.value_counts('EDUCATION_TYPE') # Cuenta la ocurrencia de cada valor único en la columna 'EDUCATION_TYPE'

data.value_counts('FAMILY_STATUS') # Cuenta la ocurrencia de cada valor único en la columna 'FAMILY_STATUS'

data.value_counts('HOUSING_TYPE') # Cuenta la ocurrencia de cada valor único en la columna 'HOUSING_TYPE'

data.value_counts('OCCUPATION_TYPE') # Cuenta la ocurrencia de cada valor único en la columna 'OCCUPATION_TYPE'

data.value_counts('ORGANIZATION_TYPE') # Cuenta la ocurrencia de cada valor único en la columna 'ORGANIZATION_TYPE'

"""#Visualización de datos"""

import matplotlib.pyplot as plt # Importa la librería Matplotlib para la creación de gráficos

plt.figure(figsize=(12,8)) # Crea una nueva figura con un tamaño específico
plt.hist(data['CREDIT'], bins = 500) # Genera un histograma de la columna 'CREDIT' con 500 barras
plt.show() # Muestra el gráfico

plt.figure(figsize=(12,8)) # Crea una nueva figura con un tamaño específico
plt.hist(data['CREDIT'], bins = 500, color='#5dc1b9') # Genera un histograma con color personalizado
plt.title("Histograma de créditos") # Añade un título al histograma
plt.show() # Muestra el gráfico

plt.figure(figsize=(12,8)) # Crea una nueva figura con un tamaño específico
plt.hist(data['CREDIT'], bins=500, density = True, cumulative= True) # Genera un histograma acumulativo y normalizado
plt.show() # Muestra el gráfico

plt.figure(figsize=(12,8)) # Crea una nueva figura con un tamaño específico
plt.hist(data['CREDIT'], bins = 500, range=(100000,2000000)) # Genera un histograma con un rango específico en el eje X
plt.show() # Muestra el gráfico

plt.figure(figsize=(12,8)) # Crea una nueva figura con un tamaño específico
plt.hist(data['CREDIT'], bins = 200, histtype= 'step', color = 'purple') # Genera un histograma de tipo 'step' (solo contornos)
plt.show() # Muestra el gráfico

plt.figure(figsize=(12,8)) # Crea una nueva figura con un tamaño específico
plt.hist(data['CREDIT'], bins = 200, histtype= 'stepfilled', color= 'pink') # Genera un histograma de tipo 'stepfilled' (relleno)
plt.show() # Muestra el gráfico

plt.figure(figsize=(12,8)) # Crea una nueva figura con un tamaño específico
plt.hist(data['CREDIT'], bins = 500, orientation='horizontal', color='brown') # Genera un histograma horizontal
plt.show() # Muestra el gráfico

plt.figure(figsize=(12,8)) # Crea una nueva figura con un tamaño específico
plt.hist(data['CREDIT'], bins = 500, color= '#aa8caf',log = True) # Genera un histograma con escala logarítmica en el eje Y
plt.show() # Muestra el gráfico

import seaborn as sns # Importa la librería Seaborn para visualización de datos

plt.figure(figsize=(10,10)) # Crea una nueva figura con un tamaño específico
sns.histplot(data['CREDIT'], bins=20) # Genera un histograma de la columna 'CREDIT' usando Seaborn
# No se necesita plt.show() aquí, ya que Seaborn a menudo lo maneja automáticamente o Matplotlib lo muestra al final.

plt.figure(figsize=(10,10)) # Crea una nueva figura con un tamaño específico
sns.histplot(data['CREDIT'], element = 'step') # Genera un histograma con un estilo de 'paso' para las barras

plt.figure(figsize=(10,10)) # Crea una nueva figura con un tamaño específico
sns.histplot(data['CREDIT'], element = 'poly', color='#5dc1b9' ) # Genera un histograma con un elemento 'poly' (polígono)

plt.figure(figsize=(10,10)) # Crea una nueva figura con un tamaño específico
sns.histplot(data['CREDIT'], element = 'poly', fill = False, color = '#5dc1b9') # Genera un histograma de polígono sin relleno

!pip install ydata-profiling # Instala la librería ydata-profiling para generar informes de perfilado de datos

from ydata_profiling import ProfileReport # Importa ProfileReport desde ydata_profiling

profile = ProfileReport(data, title="Profiling Report") # Crea un objeto ProfileReport para el DataFrame 'data'

profile.to_file('your_report.html') # Exporta el informe de perfilado a un archivo HTML

from matplotlib.lines import lineStyles # Importa lineStyles (aunque no se usa directamente en este snippet)
# PARTE 1: LA ANATOMIA MATEMATICA Y VISUAL DEL BOXPLOT (Usando la Edad)

# 1. Calculos matematicos paso a paso
Q1 = data["FAM_MEMBERS"].quantile(0.25) # Calcula el primer cuartil (Q1) de la columna 'FAM_MEMBERS'
Mediana = data["FAM_MEMBERS"].median() # Calcula la mediana de la columna 'FAM_MEMBERS'
Q3 = data["FAM_MEMBERS"].quantile(0.75) # Calcula el tercer cuartil (Q3) de la columna 'FAM_MEMBERS'
IQR = Q3 - Q1 # Calcula el Rango Intercuartílico (IQR)
limite_sup = Q3 + 1.5 * IQR # Calcula el límite superior para identificar outliers
limite_inf = Q1 - 1.5 * IQR # Calcula el límite inferior para identificar outliers

# Imprimimos el "guion" para la clase
print("--- RADIOGRAFIA DE NUMERO DE MIEMBROS FAMILIARES EN LA EMPRESA ---")
print(f"1. El Q1 (Inicio de la caja) es: {Q1:.0f} miembros familiares. El 25% de la empresa es menor a esto.")
print(f"2. El Q3 (Fin de la caja) es: {Q3:.0f} miembros familiares. El 75% de la empresa es menor a esto.")
print(f"3. La masa principal (el IQR o tamaño de la caja) esta entre {Q1:.0f} y {Q3:.0f} miembros familiares.")
print(f"4. ¡Alerta de Outlier! Segun las reglas matematicas, cualquier edad mayor a {limite_sup:.0f} miembros familiares es atipica.\n")

#2. Visualizacion Didactica: Dibujando las formulas
plt.figure(figsize=(14, 4)) # Crea una nueva figura para el gráfico con un tamaño específico
sns.boxplot(x=data["FAM_MEMBERS"], color="lightgreen", width=0.4) # Genera un boxplot de la columna 'FAM_MEMBERS'

#3. Trazamos lineas verticales para conectar los numeros con el dibujo
plt.axvline(Q1, color="blue", linestyle="--", linewidth=2, label=f'Q1 ({Q1:.0f} miembros familiares)') # Dibuja una línea vertical para Q1
plt.axvline(Q3, color="purple", linestyle="--", linewidth=2, label=f'Q3 ({Q3:.0f} miembros familiares)') # Dibuja una línea vertical para Q3
plt.axvline(limite_sup, color="red", linestyle="--", linewidth=2, label=f'Frontera Outliers Sup ({limite_sup:.0f} miembros familiares)') # Dibuja una línea vertical para el límite superior de outliers

plt.title("Anatomia de un Boxplot: ¿De donde salen las lineas de la caja?", fontsize=14, fontweight="bold") # Añade un título al boxplot
plt.xlabel("Miembros familiares de los Empleados") # Etiqueta el eje X
plt.legend() # Muestra la leyenda del gráfico
plt.show() # Muestra el gráfico

print("EXPLICACIÓN")
print("")

print(f"5. La Mediana (el centro de la caja) es: {Mediana:.0f} miembros familiares. El 50% de la empresa es menor a esto.")
print("- Vean como la caja verde empieza exactamente en la linea azul (Q1) ytermina en la morada (Q3).")
print("- El bigote derecho intenta llegar hasta el dato mas lejano, pero choca contra la 'Pared Roja' (Limite Superior).")